#Makefile for Homework #2

#Compiler and compiler flag -Xlint
JFLAGS = -g
JCC = javac

default: Square.class Test.class

Square.class:
	$(JCC) $(JFLAGS) Square.java
	
Square.class:
	$(JCC) $(JFLAGS) Test.java

	
clean:
	$(RM) *.class